accessing
recordedException: anObject

	self subclassResponsibility.